const sliderItems = [
  {
    id: 1,
    image: "/images/slider/slider1.webp",
    thumb: "/images/slider/slider1.webp",
    background: "#f6f5f0",
    title: "Collar Brooklyn",
    description: "Diseño urbano y elegante",
    price: "₡25.000",
    link: "/products/collar",
    button: "Comprar",
  },

  {
    id: 2,
    image: "/images/slider/slider2.jpg",
    thumb: "/images/slider/slider2.jpg",
    background: "#f6f5f0",
    title: "Arnés Signature",
    description: "Estilo y comodidad en uno",
    price: "₡35.000",
    link: "/products/harness-set",
    button: "Comprar",
  },

  {
    id: 3,
    image: "/images/slider/slider3.webp",
    thumb: "/images/slider/slider3.webp",
    background: "#f2f2f2",
    title: "Charm Elegance",
    description: "Un detalle que destaca",
    price: "₡40.000",
    link: "/products/charm-necklace",
    button: "Comprar",
  },

  {
    id: 4,
    image: "/images/slider/slider4.jpg",
    thumb: "/images/slider/slider4.jpg",
    background: "#131315",
    title: "Set Brooklyn",
    description: "Elegancia para cada paseo",
    price: "₡32.000",
    link: "/products/collar-set",
    button: "Comprar",
  },

  {
    id: 5,
    image: "/images/slider/slider5.webp",
    thumb: "/images/slider/slider5.webp",
    background: "#f6f5f0",
    title: "Correa blueSky",
    description: "Brillo y estilo premium",
    price: "₡28.000",
    link: "/products/correa-dorada",
    button: "Comprar",
  },

  {
    id: 6,
    image: "/images/slider/slider6.jpg",
    thumb: "/images/slider/slider6.jpg",
    background: "#ffffff",
    title: "Moño Ross",
    description: "Un toque dulce y especial",
    price: "₡12.000",
    link: "/products/mono-rosa",
    button: "Comprar",
  },

  {
    id: 7,
    image: "/images/slider/slider7.jpg",
    thumb: "/images/slider/slider7.jpg",
    background: "#131315",
    title: "Golden Lead",
    description: "Estilo que marca la diferencia",
    price: "₡15.000",
    link: "/products/correa-dorada",
    button: "Comprar",
  },
];
